### ISSUE TITLE
Add repo description

### ISSUE THREAD

**Issue by dandv** [Meggin/bamazon#1]
[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by Meggin** [comment]
Hey, Dan.

Did you mean to create this issue here?

I'm studying at the moment-- and this is a repo of one of my class assignments.

And it includes a README, so there is a repo description. Do you need something more?

Meggin

**Comment by dandv** [comment]
NVM, I saw this in your weekly snippets and thought I'd check it out.

**Comment by Meggin** [comment]
What do you think? I'm learning, so any and all feedback most welcome!

**Comment by dandv** [comment]
I think it's good practice to set a description for repos, because the descriptions appear in search results.

**Comment by Meggin** [comment]
Ah yeah, I get it. Will do! Thanks :).

**Comment by Meggin** [comment]
Fixed.
